  name: native tests

on:
  push:
    branches: [DEV, main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install platformio
        run: pip install platformio
      - name: run test
        run: pio test -e native
